INSERT INTO CONFIGURATION (PROPIEDAD, VALOR) VALUES ('1', 'Valor 1');

INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('1', 'b', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('2', 'c', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('3', 'd', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('4', 'b', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('5', 'c', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('6', 'c', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('7', 'b', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('8', 'd', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('9', 'a', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('10', 'b', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('11', 'c', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('12', 'd', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('13', 'c', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('14', 'a', '.');
INSERT INTO DAVID_PINEROS (NUMEROPREGUNTA, LETRA, JUSTIFICACION ) VALUES ('15', 'c', '.');